name: Ping Streamlit WebApp

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Send HTTP request to Streamlit app
      run: |
        curl -X GET "https://frontendpy-h24q76f4ncj9qnnd2u6zkp.streamlit.app/" -w "%{http_code}\n" -o /dev/null -s

